# Etapa 1: Construir a aplicação React (Frontend)
FROM node:18-alpine AS react-build

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o package.json e o package-lock.json para instalar as dependências
COPY ReactProntoClin/prontoclin/package*.json /app/

# Instalar as dependências
RUN npm install

# Copiar o código fonte da aplicação React
COPY ReactProntoClin/prontoclin /app/

# Instalar o Vite como dependência de desenvolvimento
RUN npm install vite --save-dev

# Construir a aplicação React para produção
RUN npm run build

# Expor a porta 3000 (do frontend)
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "run", "start"]
