CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    username VARCHAR(255),
    method VARCHAR(20) NOT NULL,
    path VARCHAR(2048) NOT NULL,
    query VARCHAR(2048),
    status INTEGER,
    duration_ms BIGINT,
    request_body TEXT
);
